name: Lotto purchase (manual)
on:
  workflow_dispatch:
jobs:
  run-purchase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          corepack enable
          pnpm install
      - name: Purchase Lotto
        id: purchase
        uses: ./
        with:
          id: ${{ secrets.ID }}
          pwd: ${{ secrets.PASSWORD }}
      - uses: rich-automation/lotto-archive-action@latest
        with:
          numbersArray: ${{ steps.purchase.outputs.numbersArray }}
          round: ${{ steps.purchase.outputs.round }}
          token: ${{ secrets.GITHUB_TOKEN }}
          debug: true
